// Generated by CoffeeScript 1.7.1
(function() {
  var cupsOfcoffee, message, _base;

  if (age > 30) {
    alert("beer");
  }

  if (age < 21) {
    alert("no beer");
  }

  if (age > 18) {
    alert("Can do stuff");
  } else {
    alert("just a kid");
  }

  if (paid() && coffee() === true) {
    pour();
  }

  if (!Decaf()) {
    addCaffeine();
  }

  if (!Decaf()) {
    addCaffeine();
  }

  message = (function() {
    switch (cupsOfCoffee) {
      case 0:
        return "asleep";
      case 1:
        return "eyes open";
      case 2:
        return "buzzed";
      default:
        return "dangerous";
    }
  })();

  if (typeof cupsOfCoffee !== "undefined" && cupsOfCoffee !== null) {
    alert("it exists");
  }

  if (typeof cupsOfcoffee !== "undefined" && cupsOfcoffee !== null) {
    alert("it exists");
  }

  if (typeof cupsOfCoffee === "undefined" || cupsOfCoffee === null) {
    cupsOfcoffee = 0;
  }

  if (typeof coffeePot !== "undefined" && coffeePot !== null) {
    coffeePot.brew();
  }

  if (typeof coffeePot !== "undefined" && coffeePot !== null) {
    coffeePot.brew();
  }

  if (typeof vehicle.start_engine === "function") {
    if (typeof (_base = vehicle.start_engine()).shift_gear === "function") {
      _base.shift_gear();
    }
  }

  if (caffeineLevel > 5) {
    alert("High Caffeine Level");
  }

  if (caffeineLevel > 5) {
    alert("Too High");
  } else {
    alert("OK");
  }

  if (!coffeeReady) {
    alert("Please wait 5 more minutes");
  }

  if ((lowLevel < newLevel && newLevel < highLevel)) {
    alert('ok');
  } else {
    alert('abnormal caffeine level');
  }

  switch (newLevel) {
    case 1:
      message = "Out of bed yet?";
      break;
    case 2:
      message = "Good morning!";
      break;
    default:
      "You should stop while you can";
  }

  if (typeof newLevel !== "undefined" && newLevel !== null) {
    checkLevel(newLevel);
  } else {
    resetLeveL();
  }

  if (typeof level !== "undefined" && level !== null) {
    if (typeof checkLevel === "function") {
      checkLevel(level);
    }
  } else {
    if (typeof resetLevel === "function") {
      resetLevel();
    }
  }

}).call(this);
