// Generated by CoffeeScript 1.7.1
(function() {
  var showNumberOfFlights;

  $(function() {
    var changeTab;
    changeTab = function(e) {
      e.preventDefault();
      $("#tabs li a.active").removeClass("active");
      return $(this).addClass("active");
    };
    return $("#tabs ul li a").click(changeTab);
  });

  $("#tabs #error a").click(function(e) {
    return e.preventDefault();
  });

  $("#confirm").queue(function() {
    return $(this).queue();
  });

  showNumberOfFlights = function(e) {
    var num_flights;
    num_flights = $(this).data('flights');
    $(this).append("<span>" + num_flights + "</span>");
    return $("#tabs span.tooltip").show();
  };

  $("#newCoffee a").click(function() {
    return alert("New coffee added");
  });

  $("#newCoffee a").click(function() {
    var name;
    name = prompt("Name of coffee: ");
    return alert("" + name);
  });

  $("#newCoffee a").click(function() {
    var coffee, name;
    name = prompt("Name of coffee:");
    coffee = $("<li>" + name + "</li>");
    return $("ul.drink").append(coffee);
  });

  $('.drink li a').click(function(e) {
    e.preventDefault();
    return alert($(this).text());
  });

  $('.drink li').mouseenter(function() {
    return $(this).find('span').show();
  });

  $('.drink li').mouseleave(function() {
    return $(this).find('span').hide();
  });

  $('.drink li').hover(function() {
    return $(this).find('span').show();
  }, function() {
    var func2;
    return func2 = $(this).find('span').hide();
  });

}).call(this);
