// Generated by CoffeeScript 1.7.1
(function() {
  var Coffee, DrinkLink, Maxgoodhouse, boring, coffee, french,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Coffee = (function() {
    function Coffee(name, strength) {
      if (strength == null) {
        strength = 1;
      }
      this.name = name;
      this.strength = strength;
    }

    return Coffee;

  })();

  Coffee = (function() {
    function Coffee(name, strength) {
      this.name = name;
      this.strength = strength != null ? strength : 1;
    }

    Coffee.prototype.brew = function() {
      return alert("Brewing " + this.name);
    };

    Coffee.prototype.pour = function(amount) {
      if (amount == null) {
        amount = 1;
      }
      if (amount === 1) {
        return "poured a single cup";
      } else {
        return "poured " + amount + " cups";
      }
    };

    return Coffee;

  })();

  french = new Coffee("french", 2);

  french.brew();

  Maxgoodhouse = (function(_super) {
    __extends(Maxgoodhouse, _super);

    function Maxgoodhouse(name, strength) {
      this.name = name;
      this.strength = strength != null ? strength : 0;
      this.brand = "Maxgoodhouse";
    }

    return Maxgoodhouse;

  })(Coffee);

  boring = new Maxgoodhouse();

  boring.brew();

  Coffee = (function() {
    function Coffee(name, level) {
      this.name = name;
      this.level = level;
    }

    Coffee.prototype.isRussian = function() {
      return this.name === 'Russian';
    };

    return Coffee;

  })();

  coffee = new Coffee('Cuban', 3);

  Coffee = (function() {
    function Coffee(name, level) {
      this.name = name;
      this.level = level != null ? level : 0;
    }

    Coffee.prototype.isRussian = function() {
      return this.name === 'Russian';
    };

    return Coffee;

  })();

  Coffee = (function(_super) {
    __extends(Coffee, _super);

    function Coffee(name, level) {
      this.name = name;
      this.level = level != null ? level : 0;
    }

    Coffee.prototype.serve = function() {
      if (this.sleeve === !true) {
        return false;
      }
      return Coffee.__super__.serve.call(this);
    };

    return Coffee;

  })(Drink);

  DrinkLink = (function() {
    function DrinkLink() {}

    DrinkLink.prototype.watchClick = function() {
      return $('a').click(function() {
        return $(this).css('color', '#F00');
      });
    };

    return DrinkLink;

  })();

  DrinkLink = (function() {
    function DrinkLink(linkClicked) {
      this.linkClicked = linkClicked != null ? linkClicked : false;
    }

    DrinkLink.prototype.watchClick = function() {
      return $('.drink a').click((function(_this) {
        return function(event) {
          $(event.target).css('color', '#F00');
          return _this.linkClicked = true;
        };
      })(this));
    };

    return DrinkLink;

  })();

}).call(this);
