// Generated by CoffeeScript 1.7.1
(function() {
  var coffee, greet, message, sum;

  message = "coffee";

  alert(message);

  coffee = function() {
    return confirm("Ready for coffeescript?");
  };

  coffee = function(message) {
    var answer;
    return answer = confirm(message);
  };

  "Your answer is " + answer;

  coffee = function() {};

  coffee = function(param, other) {};

  alert(coffee("Ready for some coffee?"));

  coffee = function(message) {
    var answer;
    if (message == null) {
      message = "Ready for some java?";
    }
    answer = confirm(message);
    return "Your answer is " + answer;
  };

  greet = function(msg) {
    return alert("Hello CoffeeScript " + msg);
  };

  greet = function(message, another) {
    return alert("" + message + " " + another);
  };

  greet = function(name) {
    if (name == null) {
      name = 'Stranger';
    }
    return alert(name);
  };

  greet = function(name) {
    if (name == null) {
      name = 'Stranger';
    }
    return "Hello, " + name;
  };

  sum = function(num1, num2) {
    return num1 + num2;
  };

}).call(this);
